### ISSUE TITLE
[QA] [0.2.1] big issue: provide the data path but MLE-agent can not use it to build models

### ISSUE THREAD

**Issue by HuaizhengZhang** [MLSysOps/MLE-agent#110]
![image](https://github.com/user-attachments/assets/083c4f10-d621-479f-905f-920310b2fafb)

![image](https://github.com/user-attachments/assets/0f96388b-2d1f-4ee4-ac42-4360fec941bb)

![image](https://github.com/user-attachments/assets/ab763812-9402-445b-823a-e9d0c0111b3a)

**Comment by HuaizhengZhang** [comment]
### the interesting thing is even the debugger finds the issue, it wont fix it but bypass it



![image](https://github.com/user-attachments/assets/87c1dafb-c4f8-4dd6-b03a-7be0c7bb8a53)



![image](https://github.com/user-attachments/assets/b2e3bebc-4625-4cb9-b506-6655e2f519ec)

**Comment by HuaizhengZhang** [comment]
### Further debug and find the issue comes from that the agent can not understand the relative path correctly. 

it can only understand the absolute path

![image](https://github.com/user-attachments/assets/59791cee-4b9f-466e-a7ba-dd3c2f72c5ef)

**Comment by huangyz0918** [comment]
It is not a bug, I didn't enable the local dataset functions
