### ISSUE TITLE
Restarting previous session

### ISSUE THREAD

**Issue by moqca** [MLSysOps/MLE-agent#121]
This can probably be immediately deleted, couldn't find the MLE agent forum anywhere.

Is there a way to restart a previous started session? 
Had a glitch with my computer mid session. Couldn't find a way to continue with the previous version without starting a new one

**Comment by HuaizhengZhang** [comment]
@leeeizhang could you take a look at this?

**Comment by leeeizhang** [comment]
> @leeeizhang could you take a look at this?

Thanks, @moqca! We may need to support the session rollback, instead of deleting the whole project for restart. And also, there will be nice to have a step log that record all processes, so users may easily rollback to any step.

```
$ mle log --project test
> 1. xxx
> 2. zxx
```

```
$ mle rollback --project test --step 2
```

@huangyz0918 how do you think about this?

**Comment by huangyz0918** [comment]
> > @leeeizhang could you take a look at this?
> 
> Thanks, @moqca! We may need to support the session rollback, instead of deleting the whole project for restart. And also, there will be nice to have a step log that record all processes, so users may easily rollback to any step.
> 
> ```
> $ mle log --project test
> > 1. xxx
> > 2. zxx
> ```
> 
> ```
> $ mle rollback --project test --step 2
> ```
> 
> @huangyz0918 how do you think about this?

We can add a local cache for each project, currently, we have a `project.yml` to store credentials under the user's workspace, we can leverage it to store some information like "which" stage/task the user is working on and the results.
