### ISSUE TITLE
[bug] agent can not understand a blur dataset name

### ISSUE THREAD

**Issue by HuaizhengZhang** [MLSysOps/MLE-agent#159]
![image](https://github.com/user-attachments/assets/7401d430-fd9e-4d2f-866a-df179f21576f)

we should guess which public dataset users want to use and list some suggested datasets, if they don't provide a clear path or name

**Comment by HuaizhengZhang** [comment]
@U-C4N

**Comment by U-C4N** [comment]
Let me try do something
