### ISSUE TITLE
[bug] generate no code

### ISSUE THREAD

**Issue by HuaizhengZhang** [MLSysOps/MLE-agent#160]
### Start a project called test-claude and planner executes very well
![image](https://github.com/user-attachments/assets/a1a4171c-d6ed-480a-b828-c94a1acc6a1c)

### However, the code is not generated. And the command is wrong, either.
![image](https://github.com/user-attachments/assets/388fc7d8-ba0a-49c6-9838-dcc122e3c635)

**Comment by huangyz0918** [comment]
Yeah, I encountered this bug sometimes, it may related to the LLM prompting

**Comment by HuaizhengZhang** [comment]
> Yeah, I encountered this bug sometimes, it may related to the LLM prompting

please have someone fix this ASAP, otherwise, it impacts the first impression so much

**Comment by huangyz0918** [comment]
@leeeizhang We need to fix a version of the openAI models, I have noticed the model has changed slightly in the behavior recently, even though the prompts are still the same, the results are different
