### ISSUE TITLE
Gemini Support

### ISSUE THREAD

**Issue by SharkLava** [MLSysOps/MLE-agent#166]
#### Software execution information

MLE-agent version:-
System OS version:-

#### Problem description
Feature Request: Gemini API support
#### Steps to reproduce the problem
- nil
#### Expected behavior
- nil
#### Other information
Would it be possible to add Google Gemini Support to the project?

**Comment by huangyz0918** [comment]
Thank you for your issue! @SharkLava 
We will add support for Gemini soon : )

**Comment by leeeizhang** [comment]
@U-C4N, would you like to take a look? thank you!

**Comment by huangyz0918** [comment]
Would you like to take a look? @leeeizhang  I think Gemini is mighty as well.

**Comment by leeeizhang** [comment]
Sure! Gemini is also important, and I will add support for it soon. Besides, I will also divide the model.py into separate items (e.g., models/openai.py, models/anthropic.py, etc.) to better organize the code.
