### ISSUE TITLE
add `mle new` -> `mle kaggle` pipeline

### ISSUE THREAD

**Issue by HuaizhengZhang** [MLSysOps/MLE-agent#178]
### refer

- https://github.com/MLSysOps/MLE-agent/pull/98/files#diff-45ae98bf9e7ae664a78357b55052f959738b29fb4377ab2aa53070060ff5f45c

#### Software execution information

MLE-agent version:
System OS version:

#### Other information

Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by huangyz0918** [comment]
I have removed the kaggle worflow in this [commit](https://github.com/MLSysOps/MLE-agent/commit/e049cd11375f5509aa02a66310360c5811b46540), if you want, you can add it back when the function is ready
