### ISSUE TITLE
[Web display] has `fail to fetch the report` issue when first run it

### ISSUE THREAD

**Issue by HuaizhengZhang** [MLSysOps/MLE-agent#180]
![image](https://github.com/user-attachments/assets/5b4ec958-9de4-470a-a440-ccabbd921699)

**Comment by huangyz0918** [comment]
Oh yes, because there is no report at the beginning. I will update the UI to handle it

**Comment by HuaizhengZhang** [comment]
![image](https://github.com/user-attachments/assets/a04b5223-47fb-44a5-a203-f114d9bb6777)

everything works well now.
