### ISSUE TITLE
[Web Display] add github setting to the web and remove all integration CLIs

### ISSUE THREAD

**Issue by HuaizhengZhang** [MLSysOps/MLE-agent#181]
#### Software execution information

MLE-agent version:
System OS version:

#### Other information

Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by HuaizhengZhang** [comment]
![image](https://github.com/user-attachments/assets/5c5b19da-d6e3-4ce6-a274-705dba789ad6)

**Comment by HuaizhengZhang** [comment]
remember to hide the token

**Comment by leeeizhang** [comment]
> ![image](https://private-user-images.githubusercontent.com/5894780/365295731-5c5b19da-d6e3-4ce6-a274-705dba789ad6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MTg0MTcsIm5iZiI6MTcyNTcxODExNywicGF0aCI6Ii81ODk0NzgwLzM2NTI5NTczMS01YzViMTlkYS1kNmUzLTRjZTYtYTI3NC03MDVkYmE3ODlhZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDdUMTQwODM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmFhMzI1OTUzYTczOGUzMzA0ZDkyZTgzYTlmYjM2YmFiMzhhYTczNWI4YTEzNTA1MjU0ZDM3ZDEzMmM1NmQ0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5UzFhkyJ9qBd8B7AJ1DN9bHIaxuUAsQLxa4wwWRQFc8)

Do we have a logo?
