### ISSUE TITLE
remove the integration CLI

### ISSUE THREAD

**Issue by HuaizhengZhang** [MLSysOps/MLE-agent#195]

**Comment by huangyz0918** [comment]
I am not sure removing it (including GitHub)  is a good idea, I trend to remove the other integrations (e.g., Google) and keep Github in the CLI. @leeeizhang

**Comment by HuaizhengZhang** [comment]
I prefer to just let users use our web UI for integrations instead of CLIs

**Comment by huangyz0918** [comment]
I decided to keep the GitHub integration in the CLI, and migrate others to the web API.

**Comment by HuaizhengZhang** [comment]
so the conclusion

### GitHub CLI
1. keep `github integration` cli there
2. but not put it into docs (too many CLIs at the beginning will confuse them)
3. Add `github token` settings to Web UI

### Other CLIs
1. migrate to web API
2. remove them from CLIs


> I decided to keep the GitHub integration in the CLI, and migrate others to the web API.

**Comment by huangyz0918** [comment]
> and I would not put it into our docs

I would recommend putting the CLI and SDK API into the document:

- First, the API document should be comprehensive (for others to contribute)
- Second, SDK/CLI is as important than the web UI to the community, so we should keep it.
