### ISSUE TITLE
[bug] Handle default branch name with `master`

### ISSUE THREAD

**Issue by huangyz0918** [MLSysOps/MLE-agent#203]
If fetching an old repo with the default branch is `master`, it will throw an API error, we need to handle this

**Comment by huangyz0918** [comment]
Would you like to take a look at this issue? @leeeizhang : )

**Comment by leeeizhang** [comment]
Sure, I can take over it! is there any methods to reproduce the issue? :)

**Comment by huangyz0918** [comment]
try this: https://github.com/huangyz0918/AndroidWM
