### ISSUE TITLE
[mle chat] cli should be redesiged

### ISSUE THREAD

**Issue by HuaizhengZhang** [MLSysOps/MLE-agent#205]
![image](https://github.com/user-attachments/assets/cac0c347-4c51-48b7-9974-b928b4ea1946)

the existing workflow has several issues

**Comment by leeeizhang** [comment]
I would like to redesign the `mle chat`, and here are some thoughts I've had:

> 1. **enable `mle chat` to execute code and debug**: users may have written their codes, and they need MLE Chat to execute and debug on these.
> 2. **allow `mle chat` to read logs and other files**: users may train multiple models with different configurations, and it would be helpful for `mle chat` to analyze training logs and suggest an optimal configuration.
> 3. **enable `mle chat` to retain conversation memory**: users can choose to return to their previous conversations when they re-enter the CLI.
> 4. **allow `mle chat` to greet users at first and inform users of its capabilities**, reducing the need for users to provide prompts at the beginning, and making the interaction more engaging.

If you have time, could you share some insights or suggestions on these? Thank you!

cc. @HuaizhengZhang, @huangyz0918

**Comment by huangyz0918** [comment]
> enable mle chat to execute code and debug: users may have written their codes, and they need MLE Chat to execute and debug on these.

I think we already have this?
