### ISSUE TITLE
[ollama] with llama3.1 can not give good plans

### ISSUE THREAD

**Issue by HuaizhengZhang** [MLSysOps/MLE-agent#207]
![image](https://github.com/user-attachments/assets/afb41902-7ad4-41e0-be56-22bef1b59b3e)

**Comment by HuaizhengZhang** [comment]
![image](https://github.com/user-attachments/assets/4606a6bf-b424-4a8c-ab39-85591011b75a)


leave more suggestions will result in a better performance

**Comment by HuaizhengZhang** [comment]
but llama3.1's hallucination is very bad

**Comment by huangyz0918** [comment]
I think the reason is this model performs bad on the JSON mode instruction
