### ISSUE TITLE
Enhance the preview function to get more comprehensive summary

### ISSUE THREAD

**Issue by leeeizhang** [MLSysOps/MLE-agent#250]
- [x] csv preview https://github.com/MLSysOps/MLE-agent/pull/249
- [ ] json preview
- [ ] yaml preview
- [x] directory preview https://github.com/MLSysOps/MLE-agent/pull/252

**Comment by huangyz0918** [comment]
In my priority list, previewing the directory is the most important thing. Assume there is a dir containing a large number of pictures (or videos, audios, etc), we cannot simply return all pictures' path (but we need a part of them), how to draw a clear file structure/pattern for LLMs meanwhile maintaining a acceptable (not scale) RAG information?
