### ISSUE TITLE
Debugging log exceeds the maximum LLM token length

### ISSUE THREAD

**Issue by huangyz0918** [MLSysOps/MLE-agent#251]
I think we should store the logs in a cache (using a vector database), and then search the most relevant logs (by embedding) for debugging.

**Comment by leeeizhang** [comment]
agree with you; RAG is helpful for analyzing logs. we can split the debugging logs into smaller sections and generate abstracts or embeddings for each item. Then, we can allow the agent to query these embeddings for analysis and debugging.

refer to: https://github.com/RehmanaYounis/Final-LogAnalysis-LLM
