### ISSUE TITLE
Add limitation to the `read_file` function

### ISSUE THREAD

**Issue by huangyz0918** [MLSysOps/MLE-agent#254]
- We have been working on the "auto" Kaggle mode for a while, we need to make sure the previous Kaggle mode is still working and fix any bugs. 
- Some of the procedures can be improved as well

**Comment by leeeizhang** [comment]
The current interactive Kaggle mode still works, but now the agent's chat history is more likely to exceed the context length limitation of gpt4o. https://github.com/MLSysOps/MLE-agent/issues/251

![image](https://github.com/user-attachments/assets/e9c1edb2-7683-4b95-b4dd-36f9ed1911d2)

**Comment by leeeizhang** [comment]
Should we add a limit to the size of the chat history (a.k.a. window memory): https://python.langchain.com/v0.1/docs/modules/memory/types/buffer_window

**Comment by huangyz0918** [comment]
> The current interactive Kaggle mode still works, but now the agent's chat history is more likely to exceed the context length limitation of gpt4o. #251
> 
> ![image](https://private-user-images.githubusercontent.com/43229014/379219231-e9c1edb2-7683-4b95-b4dd-36f9ed1911d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDQxOTMsIm5iZiI6MTcyOTcwMzg5MywicGF0aCI6Ii80MzIyOTAxNC8zNzkyMTkyMzEtZTljMWVkYjItNzY4My00Yjk1LWI0ZGQtMzZmOWVkMTkxMWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE3MTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMzRlYjc4N2MwNTYzYzYwMDQyNDBkNjgzMTc3MTdiMmRiYmE5ZmQ4YzM0MmRmNjI1ZTBlMTVjOWNjZWM0ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GmFg1BVxrFewJ0R5V5cOhRrgQ8tFexuXlt27KXGn1eM)

Could you take a look at the input prompt to see what information took so many tokens

**Comment by leeeizhang** [comment]
> > The current interactive Kaggle mode still works, but now the agent's chat history is more likely to exceed the context length limitation of gpt4o. #251
> > ![image](https://private-user-images.githubusercontent.com/43229014/379219231-e9c1edb2-7683-4b95-b4dd-36f9ed1911d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDQxOTMsIm5iZiI6MTcyOTcwMzg5MywicGF0aCI6Ii80MzIyOTAxNC8zNzkyMTkyMzEtZTljMWVkYjItNzY4My00Yjk1LWI0ZGQtMzZmOWVkMTkxMWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE3MTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMzRlYjc4N2MwNTYzYzYwMDQyNDBkNjgzMTc3MTdiMmRiYmE5ZmQ4YzM0MmRmNjI1ZTBlMTVjOWNjZWM0ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GmFg1BVxrFewJ0R5V5cOhRrgQ8tFexuXlt27KXGn1eM)
> 
> Could you take a look at the input prompt to see what information took so many tokens

I can find that the most costly prompts occur when calling the `read_file` function. The mle-agent usually calls this function to view CSV and Python files during debugging. For example, when data preprocessing fails, the mle agent always calls the `read_file` function to see all CSV data instead of calling `preview_csv_data`. We should set a limitation to the language model to call `read_file` to avoid exceeding the maximum context length.

![image](https://github.com/user-attachments/assets/b5ce70c3-32b6-425a-99a2-30a84ce7b365)

**Comment by huangyz0918** [comment]
> > > The current interactive Kaggle mode still works, but now the agent's chat history is more likely to exceed the context length limitation of gpt4o. #251
> > > ![image](https://private-user-images.githubusercontent.com/43229014/379219231-e9c1edb2-7683-4b95-b4dd-36f9ed1911d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDQxOTMsIm5iZiI6MTcyOTcwMzg5MywicGF0aCI6Ii80MzIyOTAxNC8zNzkyMTkyMzEtZTljMWVkYjItNzY4My00Yjk1LWI0ZGQtMzZmOWVkMTkxMWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE3MTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMzRlYjc4N2MwNTYzYzYwMDQyNDBkNjgzMTc3MTdiMmRiYmE5ZmQ4YzM0MmRmNjI1ZTBlMTVjOWNjZWM0ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GmFg1BVxrFewJ0R5V5cOhRrgQ8tFexuXlt27KXGn1eM)
> > 
> > 
> > Could you take a look at the input prompt to see what information took so many tokens
> 
> I can find that the most costly prompts occur when calling the `read_file` function. The mle-agent usually calls this function to view CSV and Python files during debugging. For example, when data preprocessing fails, the mle agent always calls the `read_file` function to see all CSV data instead of calling `preview_csv_data`. We should set a limitation to the language model to call `read_file` to avoid exceeding the maximum context length.
> 
> ![image](https://private-user-images.githubusercontent.com/43229014/379777036-b5ce70c3-32b6-425a-99a2-30a84ce7b365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3OTIwODksIm5iZiI6MTcyOTc5MTc4OSwicGF0aCI6Ii80MzIyOTAxNC8zNzk3NzcwMzYtYjVjZTcwYzMtMzJiNi00MjVhLTk5YTItMzBhODRjZTdiMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDE3NDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYzQ4M2NkYjc1MTM5OTBlNGRhYWQ3ZmZkMmE1YTRiNzhlZTBlYjBhMWQ0MzhhZWU2ZDNmNmQ5MTYyOTY2NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Gj6pzUvJ71Tx_8e1NdYue-Jmi7UPhr2Q3OaGRIj1AkI)

Let's first at a `limit` parameter to the `read_file` function (similar to the preview data functions) @leeeizhang. And then we should think about using RAG to search the reference
