### ISSUE TITLE
I purposely to make `self.requirement` and `self.project.requirment` different for now

### ISSUE THREAD

**Issue by HuaizhengZhang** [MLSysOps/MLE-agent#48]
to quickly debug and refactor the prompt, actually currently I add many things like data/task_type/etc to the `self.requirement` but no update them to the `self.project.requirement`

![image](https://github.com/MLSysOps/MLE-agent/assets/5894780/d6c423e1-6f3f-4f09-b5e3-b2f30d0e37a3)

will do a better org later.

**Comment by huangyz0918** [comment]
right now we are using `enhanced_requirement`
