### ISSUE TITLE
prompt session is not called

### ISSUE THREAD

**Issue by HuaizhengZhang** [MLSysOps/MLE-agent#86]
![image](https://github.com/MLSysOps/MLE-agent/assets/5894780/4754baa3-a08f-4f79-a1bf-c913702445dc)

#### Software execution information

MLE-agent version:
System OS version:

#### Other information

Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by huangyz0918** [comment]
Yeah, we only use it to save the chat history -- but not been used yet.
